name: vars-localize
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - dbus=1.13.6
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - idna=2.8=py37_1000
  - jpeg=9c
  - libedit=3.1.20181209
  - libffi=3.2.1
  # - libgcc-ng
  - libiconv=1.15
  - libpng=1.6.37
  # - libstdcxx-ng
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - ncurses=6.1
  - openssl=1.1.1d
  - pcre=8.43
  - pip=19.3.1
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.4
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.9
  - urllib3=1.25.7
  - wheel=0.33.6
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zlib=1.2.11
# prefix: /home/kevin/anaconda3/envs/vars-localize

